version: '3.3'

services:
  rstudio:
    image: rocker/tidyverse
    environment:
      - USER=${USER}
      - USERID=${USERID}
      - GROUPID=${USERID}
      - PASSWORD=${PASSWORD}
    ports:
      - "${PORT}:8787"
    volumes:
      - ${MY_PROJECTS}:/home/${USER}/projects
      - ${DATA2_PROJECTS}:${DATA2_PROJECTS}:ro
